// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

int N = Integer.parseInt(args[0]);
int greaterThanHalf = 0;
int equalorlessthanHalf = 0;

for (int i = 0; i < N; i++) {
	double random = Math.random();
	if (random > 0.5) {
		greaterThanHalf++;
	} else {
		equalorlessthanHalf++;
	}
}
System.out.println("> 0.5: " + greaterThanHalf + "times");
System.out.println("<= 0.5: " + equalorlessthanHalf + "times");

if (greaterThanHalf == 0 || equalorlessthanHalf == 0);
double count  = (double) greaterThanHalf / equalorlessthanHalf;
 System.out.println("Ratio: " + count);
}
	}